apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: klusterlet-addon-controller-acm-210
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: klusterlet-addon-controller-acm-210
    app.kubernetes.io/part-of: release-acm-210
  name: klusterlet-addon-controlljwie
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: klusterlet-addon-controller-acm-210
    weight: 100
status: {}
