apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multicluster-operators-subscription-acm-210
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multicluster-operators-subscription-acm-210
    app.kubernetes.io/part-of: release-acm-210
  name: multicluster-operators-subscription-acm-210
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multicluster-operators-subscription-acm-210
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multicluster-operators-subscription-acm-210
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-210/multicluster-operators-subscription-acm-210@sha256:97e041cb5f0a213f4bafb3d679c55e08e35405918781412fc52ef96229f93e95
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
