apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multicluster-global-hub-operator-acm-210
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multicluster-global-hub-operator-acm-210
    app.kubernetes.io/part-of: release-acm-210
  name: multicluster-global-hub-operator-acm-210
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multicluster-global-hub-operator-acm-210
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multicluster-global-hub-operator-acm-210
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-210/multicluster-global-hub-operator-acm-210@sha256:6c68b7a2582cb283ceb348903c2fc3486b44b2c0936f50fb9c9a30bbbc12d2f3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
