apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: iam-policy-controller-acm-210
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iam-policy-controller-acm-210
    app.kubernetes.io/part-of: release-acm-210
  name: iam-policy-controller-acm-210
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: iam-policy-controller-acm-210
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: iam-policy-controller-acm-210
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-210/iam-policy-controller-acm-210@sha256:566a5eb1b074ae74a9d7f97d2a465b826d33fde3dec1ab88c0545075af860edb
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
