apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: iam-policy-controller-acm-210
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-210/iam-policy-controller-acm-210@sha256:ff624b0c5d12697342a367b0432eb90fbda8652257a16bbcf568d36508a7e9cf
        name: container-image
        resources: {}
status: {}
