apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-exporter-acm-210
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-exporter-acm-210
    app.kubernetes.io/part-of: release-acm-210
  name: node-exporter-acm-210
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-exporter-acm-210
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: node-exporter-acm-210
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources: {}
status: {}
