apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: config-policy-controller-acm-210
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-210/config-policy-controller-acm-210@sha256:c03c8c268d1c2da628a0622cf81b9f0d092c397ec76a2ac990986990a4496064
        name: container-image
        resources: {}
status: {}
