apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-addon-controller-acm-210
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-210/governance-policy-addon-controller-acm-210@sha256:02fb6639cb539cca66915e4143f32dadcebeb9c1c7ba8f799f74e74fb3df8e53
        name: container-image
        resources: {}
status: {}
